import { DEPLOYMENT_ENV } from 'ergonomic-react/src/config/deploymentEnv';

export const useSiteOriginByTarget = () => {
	return {
		live: {
			HOME_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_HOME_WEB_APP,
			ADMIN_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_ADMIN_WEB_APP,
			BLOG_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_BLOG_WEB_APP,
			KNOWLEDGE_BASE_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_KNOWLEDGE_BASE_WEB_APP,
			REFERRALS_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_REFERRALS_WEB_APP,
			SSO_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_SSO_WEB_APP,
			STATUS_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_STATUS_WEB_APP,
			SUPPORT_WEB_APP: process.env.NEXT_PUBLIC_LIVE_SITE_URL_SUPPORT_WEB_APP,
		},
		test: {
			HOME_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_HOME_WEB_APP,
			ADMIN_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_ADMIN_WEB_APP,
			BLOG_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_BLOG_WEB_APP,
			KNOWLEDGE_BASE_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_KNOWLEDGE_BASE_WEB_APP,
			REFERRALS_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_REFERRALS_WEB_APP,
			SSO_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_SSO_WEB_APP,
			STATUS_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_STATUS_WEB_APP,
			SUPPORT_WEB_APP: process.env.NEXT_PUBLIC_TEST_SITE_URL_SUPPORT_WEB_APP,
		},
	}[DEPLOYMENT_ENV];
};
