import { DEPLOYMENT_ENV } from 'ergonomic-react/src/config/deploymentEnv';

export const useSiteOriginByTarget = () => {
	return {
		live: {
			HOME_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_HOME_SITE,
			ADMIN_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_ADMIN_SITE,
			BLOG_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_BLOG_SITE,
			KNOWLEDGE_BASE_SITE:
				process.env.NEXT_PUBLIC_LIVE_SITE_URL_KNOWLEDGE_BASE_SITE,
			REFERRALS_SITE:
				process.env.NEXT_PUBLIC_LIVE_SITE_URL_REFERRALS_SITE,
			SSO_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_SSO_SITE,
			STATUS_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_STATUS_SITE,
			SUPPORT_SITE: process.env.NEXT_PUBLIC_LIVE_SITE_URL_SUPPORT_SITE,
		},
		test: {
			HOME_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_HOME_SITE,
			ADMIN_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_ADMIN_SITE,
			BLOG_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_BLOG_SITE,
			KNOWLEDGE_BASE_SITE:
				process.env.NEXT_PUBLIC_TEST_SITE_URL_KNOWLEDGE_BASE_SITE,
			REFERRALS_SITE:
				process.env.NEXT_PUBLIC_TEST_SITE_URL_REFERRALS_SITE,
			SSO_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_SSO_SITE,
			STATUS_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_STATUS_SITE,
			SUPPORT_SITE: process.env.NEXT_PUBLIC_TEST_SITE_URL_SUPPORT_SITE,
		},
	}[DEPLOYMENT_ENV];
};
