import {
	AlphaVantageCompany,
	alphaVantageCompaniesApi,
} from '../models/index.js';

describe('AlphaVantageCompany', () => {
	test('exampleAlphaVantageCompany', () => {
		const { apiResourceDefaultJson } = alphaVantageCompaniesApi;
		const exampleAlphaVantageCompany: AlphaVantageCompany = {
			...apiResourceDefaultJson,
			category: 'default',
			name: 'My AlphaVantageCompany',
			'200DayMovingAverage': '',
			'50DayMovingAverage': '',
			'52WeekHigh': '',
			'52WeekLow': '',
			Address: '',
			AnalystRatingBuy: '',
			AnalystRatingHold: '',
			AnalystRatingSell: '',
			AnalystRatingStrongBuy: '',
			AnalystRatingStrongSell: '',
			AnalystTargetPrice: '',
			AssetType: '',
			Beta: '',
			BookValue: '',
			CIK: '',
			Currency: '',
			Country: '',
			Description: '',
			DividendDate: '',
			DividendPerShare: '',
			DividendYield: '',
			DilutedEPSTTM: '',
			EBITDA: '',
			EPS: '',
			EVToEBITDA: '',
			EVToRevenue: '',
			ExDividendDate: '',
			Exchange: '',
			FiscalYearEnd: '',
			ForwardPE: '',
			GrossProfitTTM: '',
			Industry: '',
			LatestQuarter: '',
			MarketCapitalization: '',
			Name: '',
			OfficialSite: '',
			OperatingMarginTTM: '',
			PEGRatio: '',
			PERatio: '',
			PriceToBookRatio: '',
			PriceToSalesRatioTTM: '',
			ProfitMargin: '',
			QuarterlyEarningsGrowthYOY: '',
			QuarterlyRevenueGrowthYOY: '',
			ReturnOnAssetsTTM: '',
			ReturnOnEquityTTM: '',
			RevenuePerShareTTM: '',
			RevenueTTM: '',
			Sector: '',
			SharesOutstanding: '',
			Symbol: '',
			TrailingPE: '',
		};
		expect(exampleAlphaVantageCompany).toEqual<
			typeof exampleAlphaVantageCompany
		>({
			_id: expect.any(String),
			_date_last_modified: expect.any(String),
			_created_by: expect.any(String),
			_object: 'alpha_vantage_company',
			category: 'default',
			_archived: false,
			_date_created: expect.any(String),
			_deleted: false,
			description: '',
			name: 'My AlphaVantageCompany',
			'200DayMovingAverage': '',
			'50DayMovingAverage': '',
			'52WeekHigh': '',
			'52WeekLow': '',
			Address: '',
			AnalystRatingBuy: '',
			AnalystRatingHold: '',
			AnalystRatingSell: '',
			AnalystRatingStrongBuy: '',
			AnalystRatingStrongSell: '',
			AnalystTargetPrice: '',
			AssetType: '',
			Beta: '',
			BookValue: '',
			CIK: '',
			Currency: '',
			Country: '',
			Description: '',
			DividendDate: '',
			DividendPerShare: '',
			DividendYield: '',
			DilutedEPSTTM: '',
			EBITDA: '',
			EPS: '',
			EVToEBITDA: '',
			EVToRevenue: '',
			ExDividendDate: '',
			Exchange: '',
			FiscalYearEnd: '',
			ForwardPE: '',
			GrossProfitTTM: '',
			Industry: '',
			LatestQuarter: '',
			MarketCapitalization: '',
			Name: '',
			OfficialSite: '',
			OperatingMarginTTM: '',
			PEGRatio: '',
			PERatio: '',
			PriceToBookRatio: '',
			PriceToSalesRatioTTM: '',
			ProfitMargin: '',
			QuarterlyEarningsGrowthYOY: '',
			QuarterlyRevenueGrowthYOY: '',
			ReturnOnAssetsTTM: '',
			ReturnOnEquityTTM: '',
			RevenuePerShareTTM: '',
			RevenueTTM: '',
			Sector: '',
			SharesOutstanding: '',
			Symbol: '',
			TrailingPE: '',
		});
	});
});
