import * as yup from 'yup';
import {
	GeneralizedApiResourceCreateParamsRequiredFieldEnum,
	GeneralizedApiResourceProperties,
	CreateParams,
	UpdateParams,
	YupHelpers,
	getApiResourceSpec,
	getEnum,
} from 'ergonomic';
import {
	apiYupHelpers,
	idPrefixByResourceName,
} from '../../utils/apiYupHelpers.js';

export const AlphaVantageCompanyCategoryEnum = getEnum(['default']);
export type AlphaVantageCompanyCategory =
	keyof typeof AlphaVantageCompanyCategoryEnum.obj;

const createParamsRequiredFieldEnum = getEnum([
	...GeneralizedApiResourceCreateParamsRequiredFieldEnum.arr,
	'200DayMovingAverage',
	'50DayMovingAverage',
	'52WeekHigh',
	'52WeekLow',
	'Address',
	'AnalystRatingBuy',
	'AnalystRatingHold',
	'AnalystRatingSell',
	'AnalystRatingStrongBuy',
	'AnalystRatingStrongSell',
	'AnalystTargetPrice',
	'AssetType',
	'Beta',
	'BookValue',
	'CIK',
	'Currency',
	'Country',
	'Description',
	'DividendDate',
	'DividendPerShare',
	'DividendYield',
	'DilutedEPSTTM',
	'EBITDA',
	'EPS',
	'EVToEBITDA',
	'EVToRevenue',
	'ExDividendDate',
	'Exchange',
	'FiscalYearEnd',
	'ForwardPE',
	'GrossProfitTTM',
	'Industry',
	'LatestQuarter',
	'MarketCapitalization',
	'Name',
	'OfficialSite',
	'OperatingMarginTTM',
	'PEGRatio',
	'PERatio',
	'PriceToBookRatio',
	'PriceToSalesRatioTTM',
	'ProfitMargin',
	'QuarterlyEarningsGrowthYOY',
	'QuarterlyRevenueGrowthYOY',
	'ReturnOnAssetsTTM',
	'ReturnOnEquityTTM',
	'RevenuePerShareTTM',
	'RevenueTTM',
	'Sector',
	'SharesOutstanding',
	'Symbol',
	'TrailingPE',
] as const);
type T = keyof typeof createParamsRequiredFieldEnum.obj;

const _object = 'alpha_vantage_company';
const properties = {
	...GeneralizedApiResourceProperties,
	_id: apiYupHelpers.id(_object),
	_object: YupHelpers.constant(_object),
	category: AlphaVantageCompanyCategoryEnum.getDefinedSchema(),
	'200DayMovingAverage': yup.string().nullable().default(null),
	'50DayMovingAverage': yup.string().nullable().default(null),
	'52WeekHigh': yup.string().nullable().default(null),
	'52WeekLow': yup.string().nullable().default(null),
	Address: yup.string().nullable().default(null),
	AnalystRatingBuy: yup.string().nullable().default(null),
	AnalystRatingHold: yup.string().nullable().default(null),
	AnalystRatingSell: yup.string().nullable().default(null),
	AnalystRatingStrongBuy: yup.string().nullable().default(null),
	AnalystRatingStrongSell: yup.string().nullable().default(null),
	AnalystTargetPrice: yup.string().nullable().default(null),
	AssetType: yup.string().nullable().default(null),
	Beta: yup.string().nullable().default(null),
	BookValue: yup.string().nullable().default(null),
	CIK: yup.string().nullable().default(null),
	Currency: yup.string().nullable().default(null),
	Country: yup.string().nullable().default(null),
	Description: yup.string().nullable().default(null),
	DividendDate: yup.string().nullable().default(null),
	DividendPerShare: yup.string().nullable().default(null),
	DividendYield: yup.string().nullable().default(null),
	DilutedEPSTTM: yup.string().nullable().default(null),
	EBITDA: yup.string().nullable().default(null),
	EPS: yup.string().nullable().default(null),
	EVToEBITDA: yup.string().nullable().default(null),
	EVToRevenue: yup.string().nullable().default(null),
	ExDividendDate: yup.string().nullable().default(null),
	Exchange: yup.string().nullable().default(null),
	FiscalYearEnd: yup.string().nullable().default(null),
	ForwardPE: yup.string().nullable().default(null),
	GrossProfitTTM: yup.string().nullable().default(null),
	Industry: yup.string().nullable().default(null),
	LatestQuarter: yup.string().nullable().default(null),
	MarketCapitalization: yup.string().nullable().default(null),
	Name: yup.string().nullable().default(null),
	OfficialSite: yup.string().nullable().default(null),
	OperatingMarginTTM: yup.string().nullable().default(null),
	PEGRatio: yup.string().nullable().default(null),
	PERatio: yup.string().nullable().default(null),
	PriceToBookRatio: yup.string().nullable().default(null),
	PriceToSalesRatioTTM: yup.string().nullable().default(null),
	ProfitMargin: yup.string().nullable().default(null),
	QuarterlyEarningsGrowthYOY: yup.string().nullable().default(null),
	QuarterlyRevenueGrowthYOY: yup.string().nullable().default(null),
	ReturnOnAssetsTTM: yup.string().nullable().default(null),
	ReturnOnEquityTTM: yup.string().nullable().default(null),
	RevenuePerShareTTM: yup.string().nullable().default(null),
	RevenueTTM: yup.string().nullable().default(null),
	Sector: yup.string().nullable().default(null),
	SharesOutstanding: yup.string().nullable().default(null),
	Symbol: yup.string().defined().meta({ unique_key: true }),
	TrailingPE: yup.string().nullable().default(null),
} as const;
type U = typeof properties;

export const alphaVantageCompaniesApi = getApiResourceSpec<keyof U, U, T>({
	createParamsRequiredFieldEnum,
	idPrefix: idPrefixByResourceName[_object],
	properties,
	resourceNamePlural: 'alpha_vantage_companies',
} as const);
export type AlphaVantageCompany = yup.InferType<
	typeof alphaVantageCompaniesApi.apiResourceJsonSchema
>;
export type CreateAlphaVantageCompanyParams = CreateParams<
	AlphaVantageCompany,
	T
>;
export type UpdateAlphaVantageCompanyParams = UpdateParams<AlphaVantageCompany>;
