import { getApiResourceYupHelpers } from 'ergonomic';

export const idPrefixByResourceName = {
	ach_transfer: 'ach_tf',
	asset: 'ast',
	asset_order: 'ast_ord',
	asset_price: 'ast_pr',
	bank_account: 'bnk',
	identity_verification_document: 'id_ver',
	invoice: 'inv',
	license: 'lic',
	model: 'mod',
	model_family: 'mod_fm',
	news_report: 'rep',
	open_ai_model: 'opai_mod',
	open_ai_model_family: 'opai_mod_fm',
	order: 'ord',
	parameter: 'param',
	position: 'pos',
	recommendation: 'rec',
	user: 'usr',
} as const;
export const apiYupHelpers = getApiResourceYupHelpers(
	[
		'ach_transfer',
		'asset',
		'asset_order',
		'asset_price',
		'bank_account',
		'identity_verification_document',
		'invoice',
		'license',
		'model',
		'model_family',
		'news_report',
		'open_ai_model',
		'open_ai_model_family',
		'order',
		'parameter',
		'position',
		'recommendation',
		'user',
	],
	idPrefixByResourceName,
);
