import { secrets } from './secrets.js';
import serverVariablesLive from './serverVariables.live.json' assert { type: 'json' };
import serverVariablesTest from './serverVariables.test.json' assert { type: 'json' };

const { SECRET_CRED_DEPLOYMENT_ENVIRONMENT, SECRET_CRED_SERVER_PROTOCOL } =
	secrets;

export const variables =
	SECRET_CRED_DEPLOYMENT_ENVIRONMENT === 'live'
		? serverVariablesLive
		: serverVariablesTest;

export const siteOriginByTarget = {
	HOME_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.HOME_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	ADMIN_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.ADMIN_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	BLOG_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.BLOG_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	KNOWLEDGE_BASE_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.KNOWLEDGE_BASE_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	REFERRALS_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.REFERRALS_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	SSO_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.SSO_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	STATUS_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.STATUS_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
	SUPPORT_SITE:
		variables.SERVER_VAR_SITE_ORIGIN_BY_PROTOCOL_BY_TARGET.SUPPORT_SITE[
			SECRET_CRED_SERVER_PROTOCOL
		],
};

export const restApiOrigin =
	SECRET_CRED_SERVER_PROTOCOL === 'http'
		? variables.SERVER_VAR_REST_API_ORIGIN_HTTP
		: variables.SERVER_VAR_REST_API_ORIGIN_HTTPS;
