import { GeneralizedSecretData } from 'ergonomic-node';

export type SecretData = GeneralizedSecretData & {
	SECRET_CRED_ALPACA_BROKER_API_BASE_URL: string;
	SECRET_CRED_ALPACA_BROKER_API_KEY: string;
	SECRET_CRED_ALPACA_BROKER_API_SECRET: string;
	SECRET_CRED_ALPACA_BROKER_ESTIMATION_ACCOUNT_ID: string;
	SECRET_CRED_ALPACA_BROKER_ESTIMATION_API_BASE_URL: string;
	SECRET_CRED_ALPACA_BROKER_ESTIMATION_API_KEY: string;
	SECRET_CRED_ALPACA_BROKER_ESTIMATION_API_SECRET: string;
	SECRET_CRED_ALPACA_OAUTH_API_BASE_URL: string;
	SECRET_CRED_ALPACA_OAUTH_CLIENT_ID: string;
	SECRET_CRED_ALPACA_OAUTH_CLIENT_SECRET: string;
	SECRET_CRED_ALPHA_VANTAGE_API_KEY: string;
	SECRET_CRED_FIRESTORE_DATABASE_ENCRYPTION_KEY: string;
	SECRET_CRED_GMAIL_API_DEVELOPER_ALERTS_SEND_FROM_EMAIL: string;
	SECRET_CRED_GMAIL_API_DEVELOPER_ALERTS_SEND_FROM_NAME: string;
	SECRET_CRED_GMAIL_API_DEVELOPER_ALERTS_USER_ID: string;
	SECRET_CRED_OPENAI_API_KEY: string;
	SECRET_CRED_RESEARCH_ACCEPTANCE_LETTER_DOWNLOAD_URL_FALL: string;
	SECRET_CRED_RESEARCH_ACCEPTANCE_LETTER_DOWNLOAD_URL_SUMMER: string;
};
