import { GeneralizedSecretData } from 'ergonomic-node';

export type SecretData = GeneralizedSecretData & {
	SECRET_CRED_ALPACA_BROKER_API_BASE_URL: string;
	SECRET_CRED_ALPACA_BROKER_API_KEY: string;
	SECRET_CRED_ALPACA_BROKER_API_SECRET: string;
	SECRET_CRED_ALPHA_VANTAGE_API_KEY: string;
	SECRET_CRED_FIRESTORE_DATABASE_ENCRYPTION_KEY: string;
	SECRET_CRED_OPENAI_API_KEY: string;
	SECRET_CRED_STRIPE_API_KEY: string;
	SECRET_CRED_STRIPE_PRO_LICENSE_PRODUCT_ID: string;
	SECRET_CRED_STRIPE_PRO_LICENSE_PRODUCT_MONTHLY_PRICE_ID: string;
};
