name: Deploy Home Web App to Firebase Hosting

'on':
  push:
    branches:
      - master
      - staging

jobs:
  deploy-home-web-app:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'master' && 'live' || 'test' }}

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      SECRET_CRED_DEPLOYMENT_ENVIRONMENT: ${{ secrets.SECRET_CRED_DEPLOYMENT_ENVIRONMENT }}
      SECRET_CRED_FIREBASE_ADMIN_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.SECRET_CRED_FIREBASE_ADMIN_SERVICE_ACCOUNT_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get the commit message which triggered this run
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%B" | tr '\n' '::::')
          echo "Commit message: $COMMIT_MESSAGE"
          echo "GIT_COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - id: check_commit
        uses: ./.github/actions/check-commit-message
        with:
          commit_message: ${{ env.GIT_COMMIT_MESSAGE }}

      - name: Build Docker image
        if: env.SKIP_BUILD == 'false' && (env.DEPLOY_ALL_WEB_APPS == 'true' || env.DEPLOY_HOME_WEB_APP == 'true')
        run: docker build -t monorepo-image .

      - name: Deploy web-app:home-web-app
        if: env.SKIP_BUILD == 'false' && (env.DEPLOY_ALL_WEB_APPS == 'true' || env.DEPLOY_HOME_WEB_APP == 'true')
        run: |
          chmod +x ./scripts/deploy-firebase-hosting-site.sh;
          ./scripts/deploy-firebase-hosting-site.sh home-web-app ${{ github.ref_name == 'master' && 'app-wallot-production' || 'app-wallot-staging' }};
